global:
  imagePullSecrets:
    - name: regcred
  ingress:
    host: ${API_INGRESS_URL}
    className: internal-nginx
    annotations:
      kubernetes.io/ingress.class: "internal-nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      # CORS-related annotations
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Origin"
      nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Length,Content-Range"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-max-age: "86400"
      # SSL/TLS settings
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/hsts: "true"
      nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
      nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"

applications:
  ingress:
    path: "/applications(/|$)(.*)"
    pathType: ImplementationSpecific
    enabled: true
  serviceConfig:
    root_path: "/applications"
    prefix_url: cfg/apps

  image:
    #repository: nvcr.io/nvidian/omniverse/nv-ov-svc-applications
    repository: nvcr.io/nvidia/omniverse/kit-appstreaming-applications
    pullPolicy: Always
    tag: 1.8.0
  applications: {}
  profiles: {}
  monitoring:
    # -- Enables the creation of ServiceMonitor resource.
    enabled: false
    # -- Prometheus namespace.
    prometheusNamespace: omni-streaming